version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: krisgeus/docker-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "2181:2181"
    environment:
      ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTERNAL://:9093"
      LISTENERS: "PLAINTEXT://:9092,INTERNAL://:9093"
      SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
      INTER_BROKER: "INTERNAL"
      KAFKA_CREATE_TOPICS: "EventFromMicroserviceA:1:1"

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9093"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

networks: 
  net:
    driver: bridge